### ISSUE TITLE
css with button in options

### ISSUE THREAD

**Issue by makaria** [makaria/zaima#9]
When mouse hover the button, background && color will change, which is unexpected.

**Comment by banyudu** [comment]
In the mainfest.json file, styles from **chrome_style** overrides option.css 

 
    "options_ui": {
        "page": "html/options.html",
        "chrome_style": true
      }


Just remove the **chrome_style** line, and hover effects should disappear.

**Comment by banyudu** [comment]
Fixed in https://github.com/makaria/LiveTV/pull/11/commits/cdcee85dfc29cf7c310b4b79a752dd1793a8dda7
